"""user password_hash + nullable social fields

Revision ID: 6fda58a1c441
Revises: 9ead505faafe
Create Date: 2026-07-10 17:34:39.135662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6fda58a1c441'
down_revision: Union[str, Sequence[str], None] = '9ead505faafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.alter_column('users', 'provider',
               existing_type=postgresql.ENUM('KAKAO', 'GOOGLE', 'APPLE', name='auth_provider'),
               nullable=True)
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'provider_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'provider',
               existing_type=postgresql.ENUM('KAKAO', 'GOOGLE', 'APPLE', name='auth_provider'),
               nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
