"""blog_posts author_id nullable

Revision ID: 9ead505faafe
Revises: 3df33e164159
Create Date: 2026-07-10 17:11:51.547463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ead505faafe'
down_revision: Union[str, Sequence[str], None] = '3df33e164159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('blog_posts_author_id_fkey'), 'blog_posts', type_='foreignkey')
    op.create_foreign_key(None, 'blog_posts', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.create_foreign_key(op.f('blog_posts_author_id_fkey'), 'blog_posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.alter_column('blog_posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
