"""boards comments_enabled

Revision ID: cf0877c663a1
Revises: 6fda58a1c441
Create Date: 2026-07-11 16:25:14.915066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0877c663a1'
down_revision: Union[str, Sequence[str], None] = '6fda58a1c441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('comments_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'comments_enabled')
    # ### end Alembic commands ###
